#166 Chat API
MarianMalvin/phoqer pull request #174
Opened 2021-05-30 20:30 UTC by iMykhailychenko

2021-05-30 20:31 UTC, iMykhailychenko commented
CREATE TABLE chats(
	chat_id INT GENERATED ALWAYS AS IDENTITY, 
	author_id INT,
	client_id INT,
	offer_id uuid, 
	creation_datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	is_done BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(chat_id),
	CONSTRAINT fk_author
      FOREIGN KEY(author_id)
	  REFERENCES users_user(id)
	  ON DELETE CASCADE,
	CONSTRAINT fk_client
      FOREIGN KEY(client_id)
	  REFERENCES users_user(id)
	  ON DELETE CASCADE,
	CONSTRAINT fk_offer
      FOREIGN KEY(offer_id)
	  REFERENCES offers_offer(id)
	  ON DELETE CASCADE
);

CREATE TABLE messages(
	id INT GENERATED ALWAYS AS IDENTITY, 
	text TEXT,
	chat_id INT,
	author_id INT,
	creation_datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	is_red BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(id),
	CONSTRAINT fk_chat
      FOREIGN KEY(chat_id)
	  REFERENCES chats(chat_id)
	  ON DELETE CASCADE,
	CONSTRAINT fk_author
      FOREIGN KEY(author_id)
	  REFERENCES users_user(id)
	  ON DELETE CASCADE
);

CREATE TABLE messages_uploads(
	access_url VARCHAR(200),
	message_id INT,
	CONSTRAINT fk_message
      FOREIGN KEY(message_id)
	  REFERENCES messages(id)
	  ON DELETE CASCADE
	CONSTRAINT fk_chat
      FOREIGN KEY(chat_id)
	  REFERENCES chats(chat_id)
	  ON DELETE CASCADE
);

2021-05-30 20:31 UTC, iMykhailychenko commented
вот тебе таблицы, на всякий

2021-05-30 20:33 UTC, iMykhailychenko commented
отступы редактор гитхаба поубирал, но и так должны работать

2021-06-01 12:56 UTC, MarianMalvin requested changes
Красота нечеловечная! Но есть пару моментов )

2021-06-01 12:56 UTC, MarianMalvin commented on FastAPI/chats/chats.py
> +        "data": [MessagesList(**message, uploads=uploads.get(message["id"], []), ) for message in messages],
А зачем эта запятая ?
```
...["id"], []), ) for...
              ^
```

2021-06-01 12:56 UTC, MarianMalvin commented on FastAPI/chats/crud.py
> +    OFFSET :offset
Добавь где-то тут комментарий перед запросом 
""" 
 Дорогой мейнтейнер:
 
 Когда ты закончишь «оптимизировать» этот запрос
 и поймешь, насколько большой ошибкой было делать это,
 пожалуйста, увеличь счетчик внизу как предупреждение
 для следующего парня:

 total_hours_wasted_here = 42
"""

2021-06-01 12:56 UTC, MarianMalvin commented on FastAPI/chats/crud.py
> +    INNER JOIN users_user ON users_user.id = messages.author_id
а почему только автора ? Тут разве не нужно такую же логику как и для get_chats ты писал ? с динамическим JOIN ?

2021-06-01 12:56 UTC, MarianMalvin commented on FastAPI/chats/chats.py
> +    if chat.get("author_id") != user_id and chat.get("client_id") != user_id:
Вот так по-моему красивее
`if not user_id in (chat.get("author_id"), chat.get("client_id"):`

2021-06-01 12:56 UTC, MarianMalvin commented on FastAPI/chats/chats.py
> +    if not chat:
вообще не замечание, просто чтобы ты знал, что это можно так же написать вот так:
```
if not chat := await crud.is_chat_exist(chat_id):
```

2021-06-01 13:16 UTC, iMykhailychenko commented on FastAPI/chats/crud.py
> +    INNER JOIN users_user ON users_user.id = messages.author_id
messages.author_id это ид автора сообщения, у нас сообщения принадлежат только одному юзеру, а чат двоим юзерам и там уже нужно жонглировать

2021-06-01 13:18 UTC, iMykhailychenko commented on FastAPI/chats/crud.py
> +    OFFSET :offset
![IMAGE 2021-06-01 16:17:55](https://user-images.githubusercontent.com/50461642/120329887-f600fa00-c2f4-11eb-9ef1-6d06b0caf52e.jpg)
ссылку на эту картинку добавлю

2021-06-01 13:30 UTC, iMykhailychenko commented on FastAPI/chats/chats.py
> +    if not chat:
<img width="455" alt="Screenshot 2021-06-01 at 16 29 15" src="https://user-images.githubusercontent.com/50461642/120331507-82f88300-c2f6-11eb-9c1a-e56c422b39c9.png">

неа

2021-06-01 18:39 UTC, MarianMalvin commented on FastAPI/chats/crud.py
> +    INNER JOIN users_user ON users_user.id = messages.author_id
точняк !

2021-06-01 18:41 UTC, MarianMalvin commented on FastAPI/chats/crud.py
> +    OFFSET :offset
Вот что-бы у меня в компании так CR проходили, что-бы можно было мемчиками по перебрасываться 🤣

2021-06-01 18:42 UTC, MarianMalvin commented on FastAPI/chats/chats.py
> +    if not chat:
hold my beer...

2021-06-01 18:47 UTC, MarianMalvin commented on FastAPI/chats/chats.py
> +    if not chat:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/22667729/120374691-26a75a80-c31a-11eb-942d-9f2851f3f4c6.png">
взять в дужки оказывается нужно было

2021-06-01 19:25 UTC, iMykhailychenko commented on FastAPI/chats/chats.py
> +    if not chat:
Принимай уже pr, сколько можно выделываться!?

2021-06-01 19:28 UTC, iMykhailychenko commented on FastAPI/chats/chats.py
> +    if not chat:
ну или зови Егора пусть еще посмотрит где нужно переносы строки вставить

2021-06-02 17:02 UTC, merged